import { Injectable } from '@angular/core';
import { RefDesign } from '../models/ref-design.model';
import { TopRd } from '../models/top-rd.model';


@Injectable()
export class RefDesignService {


  private allRds: RefDesign[] = [
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' },
    { name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics' }
  ];

  private topRds: TopRd[] = [
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/16/49/578/txn_/manual/tida-00675_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/20/42/843/txn_/manual/tida-00556_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/20/42/843/txn_/manual/tida-00556_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/14/48/412/txn_/manual/pmp10467_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/20/42/843/txn_/manual/tida-00556_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/14/48/412/txn_/manual/pmp10467_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/2/24/7/22/24/257/txn_/manual/ads54j69evm_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: '3.3V RS-485 Transceiver for Computers & Peripherals', man: 'Texas Instruments', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/20/42/843/txn_/manual/tida-00556_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/2/24/7/22/24/257/txn_/manual/ads54j69evm_fig.1.jpg', manId: 'rrr' },
    { id: 'tida-00675-power-reduction-using-dynamic-switching-reference-design-132700.html', name: 'STM32 MCU Development System for Industrial', man: 'STMicroelectronics', imageUrl: 'http://download.siliconexpert.com/pdfs/2016/1/24/0/14/48/412/txn_/manual/pmp10467_fig.1.jpg', manId: 'rrr' }

  ];

  public getAllRds(pageNum: number, pageSize: number) {
    return this.allRds.slice((pageNum * pageSize), (pageNum * pageSize) + pageSize);
  }


  public getTopRdsByMan(manName: string) {
    return this.topRds.slice();
  }



}

